name: Deploy to Staging

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: 🚀 Deploy to Staging
        run: |
          echo "Deploying to staging environment..."
          # Aqui você adiciona seus comandos de deploy
          # Ex: ssh, kubectl, serverless, etc.
